# The URL the site will be built for
base_url = "https://stigsen.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

author = "Benjamin Stigsen"
generate_feeds = true
feed_limit = 20

minify_html = true

# external_links_target_blank = true

# taxonomies = [{name = "tags"}]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
lazy_async_image = true

highlight_code = true
highlight_theme = "css"

external_links_target_blank = true


[extra]
keywords = []
